name: base
channels:
  - https://anaconda.org/pytorch3d/pytorch3d/0.7.4/download
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2022.10=py39_2
  - _ipyw_jlab_nb_ext_conf=0.1.0=py39h06a4308_1
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py39_5
  - anaconda-client=1.11.0=py39h06a4308_0
  - anaconda-navigator=2.3.1=py39h06a4308_0
  - anaconda-project=0.11.1=py39h06a4308_0
  - anyio=3.5.0=py39h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - arrow=1.2.2=pyhd3eb1b0_0
  - astroid=2.11.7=py39h06a4308_0
  - astropy=5.1=py39h7deecbd_0
  - atomicwrites=1.4.0=py_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py39h5eee18b_1
  - beautifulsoup4=4.11.1=py39h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bitarray=2.5.1=py39h5eee18b_0
  - bkcharts=0.2=py39h06a4308_1
  - black=22.6.0=py39h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h4ff587b_1
  - bokeh=2.4.3=py39h06a4308_0
  - boto3=1.24.28=py39h06a4308_0
  - botocore=1.27.28=py39h06a4308_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.15.1=py39h74dc2b5_0
  - cfitsio=3.470=h5893167_7
  - chardet=4.0.0=py39h06a4308_1003
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py39h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py39h06a4308_1
  - colorama=0.4.5=py39h06a4308_0
  - colorcet=3.0.0=py39h06a4308_0
  - conda=22.9.0=py39hf3d152e_2
  - conda-build=3.22.0=py39h06a4308_0
  - conda-content-trust=0.1.3=py39h06a4308_0
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.9.0=py39h5eee18b_0
  - conda-repo-cli=1.0.20=py39h06a4308_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - constantly=15.1.0=pyh2b92418_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=37.0.1=py39h9ce1e76_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - curl=7.84.0=h5eee18b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=0.29.32=py39h6a678d5_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - daal4py=2021.6.0=py39h79cecc1_1
  - dal=2021.6.0=hdb19cb5_916
  - dask=2022.7.0=py39h06a4308_0
  - dask-core=2022.7.0=py39h06a4308_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - datashader=0.14.1=py39h06a4308_0
  - datashape=0.5.4=py39h06a4308_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.4=pyhd3eb1b0_0
  - distributed=2022.7.0=py39h06a4308_0
  - docutils=0.18.1=py39h06a4308_3
  - entrypoints=0.4=py39h06a4308_0
  - et_xmlfile=1.1.0=py39h06a4308_0
  - expat=2.7.0=h5888daf_0
  - fftw=3.3.9=h27cfd23_1
  - filelock=3.6.0=pyhd3eb1b0_0
  - flake8=4.0.1=pyhd3eb1b0_1
  - flask=1.1.2=pyhd3eb1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freeimage=3.18.0=h88c329d_7
  - freetype=2.12.1=hca18f0e_0
  - future=0.18.2=py39h06a4308_1
  - gensim=4.1.2=py39h295c915_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - greenlet=1.1.1=py39h295c915_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - h5py=3.7.0=py39h737f45e_0
  - hdf5=1.10.6=h3ffc7dd_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.15.0=py39h06a4308_0
  - hvplot=0.8.0=py39h06a4308_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - ilmbase=2.5.5=h3f2d84a_1
  - imagecodecs=2021.8.26=py39hf0132c2_1
  - imagesize=1.4.1=py39h06a4308_0
  - importlib-metadata=4.11.3=py39h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py39h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.5=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.15.2=py39h06a4308_0
  - ipython=7.31.1=py39h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jbig=2.1=h7f98852_2003
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jedi=0.18.1=py39h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py39h7f8727e_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - jpeg=9e=h7f8727e_0
  - jq=1.6=h27cfd23_1000
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.3.4=py39h06a4308_0
  - jupyter_console=6.4.3=pyhd3eb1b0_0
  - jupyter_server=1.18.1=py39h06a4308_0
  - jupyterlab=3.4.4=py39h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - keyring=23.4.0=py39h06a4308_0
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lazy-object-proxy=1.6.0=py39h27cfd23_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.6.1=hab531cd_0
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libclang=10.0.1=default_hb85057a_2
  - libcurl=7.84.0=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.3=he6710b0_2
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=15.1.0=h767d61c_3
  - libidn2=2.3.2=h7f8727e_0
  - liblief=0.11.5=h295c915_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_5
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libpq=12.9=h16c4e8d_3
  - libraw=0.20.2=h10796ff_1
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzlib=1.2.13=h4ab18f5_6
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py39h06a4308_0
  - lxml=4.9.1=py39h1edc446_0
  - lz4=3.1.3=py39h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - markdown=3.3.4=py39h06a4308_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=mpich
  - mpich=3.3.2=external_0
  - mpmath=1.2.1=py39h06a4308_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - multipledispatch=0.6.0=py39h06a4308_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39h06a4308_1
  - navigator-updater=0.3.0=py39h06a4308_0
  - nbclassic=0.3.5=pyhd3eb1b0_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbconvert=6.4.4=py39h06a4308_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.5=py39h06a4308_0
  - networkx=2.8.4=py39h06a4308_0
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.12=py39h06a4308_0
  - nspr=4.33=h295c915_0
  - nss=3.74=h0370c37_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpydoc=1.4.0=py39h06a4308_0
  - occt=7.8.1=novtk_he2768ca_103
  - olefile=0.46=pyhd3eb1b0_0
  - oniguruma=6.9.7.1=h27cfd23_0
  - openexr=2.5.5=hf817b99_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.10=py39h5eee18b_0
  - openssl=1.1.1w=hd590300_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.13.1=py39h06a4308_0
  - param=1.12.0=pyhd3eb1b0_0
  - parsel=1.6.0=py39h06a4308_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.13=h295c915_0
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pathspec=0.9.0=py39h06a4308_0
  - patsy=0.5.2=py39h06a4308_1
  - pcre=8.45=h295c915_0
  - pep8=1.7.1=py39h06a4308_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.2.2=py39h06a4308_0
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - platformdirs=2.5.2=py39h06a4308_0
  - plotly=5.9.0=py39h06a4308_0
  - pluggy=1.0.0=py39h06a4308_1
  - ply=3.11=py39h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.11.5=py39h295c915_1
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.4.8=py39h06a4308_1
  - pycurl=7.45.1=py39h8f2d780_0
  - pydispatcher=2.0.5=py39h06a4308_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyerfa=2.0.0=py39h27cfd23_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pyjwt=2.4.0=py39h06a4308_0
  - pylint=2.14.5=py39h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyodbc=4.0.34=py39h6a678d5_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=py39h06a4308_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyqtwebengine=5.15.7=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=py39h06a4308_0
  - pytables=3.6.1=py39h77479fe_1
  - pytest=7.1.2=py39h06a4308_0
  - python=3.9.13=haa1d7c7_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.2.1=py39h06a4308_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.5.0=py39h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.0=py39h2531618_3
  - python_abi=3.9=2_cp39
  - pythonocc-core=7.8.1.1=novtk_h5981d98_100
  - pytorch3d=0.7.4=py39_cu118_pyt201
  - pytz=2022.1=py39h06a4308_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py39h7f8727e_1
  - pyzmq=23.2.0=py39h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.3.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - qtwebkit=5.212=h4eab89a_4
  - queuelib=1.5.0=py39h06a4308_0
  - rapidjson=1.1.0.post20240409=h3f2d84a_2
  - readline=8.1.2=h7f8727e_1
  - regex=2022.7.9=py39h5eee18b_0
  - requests=2.28.1=py39h06a4308_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - ripgrep=13.0.0=hbdeaff8_0
  - rope=0.22.0=pyhd3eb1b0_0
  - rtree=0.9.7=py39h06a4308_1
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - s3transfer=0.6.0=py39h06a4308_0
  - scikit-learn-intelex=2021.6.0=py39h06a4308_0
  - scrapy=2.6.2=py39h06a4308_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - secretstorage=3.3.1=py39h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=63.4.1=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py39h06a4308_0
  - snappy=1.1.9=h295c915_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=5.0.2=py39h06a4308_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.3.3=py39h06a4308_0
  - spyder-kernels=2.3.3=py39h06a4308_0
  - sqlalchemy=1.4.39=py39h5eee18b_0
  - sqlite=3.39.3=h5082296_0
  - statsmodels=0.13.2=py39h7f8727e_0
  - svgwrite=1.4.3=pyhd8ed1ab_1
  - tabulate=0.8.10=py39h06a4308_0
  - tbb=2021.6.0=hdb19cb5_0
  - tbb4py=2021.6.0=py39hdb19cb5_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py39h06a4308_1
  - terminado=0.13.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.12=h1ccaba5_0
  - tldextract=3.2.0=pyhd3eb1b0_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py39h06a4308_0
  - tomlkit=0.11.1=py39h06a4308_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.1=py39h06a4308_0
  - twisted=22.2.0=py39h5eee18b_1
  - typing_extensions=4.3.0=py39h06a4308_0
  - tzdata=2022c=h04d1e81_0
  - ujson=5.4.0=py39h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - unixodbc=2.3.11=h5eee18b_0
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py39h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py39h06a4308_1
  - wget=1.21.3=h0b77cf5_0
  - whatthepatch=1.0.2=py39h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h5eee18b_0
  - wurlitzer=3.0.2=py39h06a4308_0
  - xarray=0.20.1=pyhd3eb1b0_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=3.0.3=pyhd3eb1b0_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.2.6=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zict=2.1.0=py39h06a4308_0
  - zipp=3.8.0=py39h06a4308_0
  - zlib=1.2.13=h4ab18f5_6
  - zope=1.0=py39h06a4308_1
  - zope.interface=5.4.0=py39h7f8727e_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - attrs==25.3.0
    - axial-positional-embedding==0.2.1
    - cement==3.0.4
    - clip==1.0
    - cmake==3.25.0
    - colorlog==6.9.0
    - comm==0.2.3
    - configargparse==1.7.1
    - contourpy==1.3.0
    - dash==3.2.0
    - deprecated==1.2.18
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - efficientnet-pytorch==0.7.1
    - einops==0.8.0
    - eval-type-backport==0.2.2
    - exceptiongroup==1.3.0
    - freia==0.2
    - fsspec==2024.6.1
    - ftfy==6.3.1
    - gitdb==4.0.11
    - gitpython==3.1.43
    - grpcio==1.65.1
    - h11==0.16.0
    - habitat-sim==0.2.5
    - hipart==1.0.4
    - httpcore==1.0.9
    - httpx==0.27.2
    - huggingface-hub==0.24.2
    - ignite==1.1.0
    - imageio==2.37.0
    - imgaug==0.4.0
    - importlib-resources==6.5.2
    - ipywidgets==8.1.7
    - joblib==1.5.1
    - jupyter-core==5.8.1
    - jupyterlab-widgets==3.0.15
    - kdepy==1.1.12
    - lazy-loader==0.4
    - lit==15.0.7
    - llvmlite==0.43.0
    - local-attention==1.9.14
    - markupsafe==3.0.2
    - matplotlib==3.7.0
    - nbformat==5.10.4
    - numba==0.60.0
    - numpy==1.23.5
    - numpy-quaternion==2023.0.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-ml-py==13.580.65
    - nvidia-nccl-cu11==2.20.5
    - nvidia-nvtx-cu11==11.8.86
    - nvitop==1.5.3
    - occ==0.0.2.dev20190912195130
    - omegaconf==2.3.0
    - open-clip-torch==2.26.1
    - open3d==0.18.0
    - openai==1.35.3
    - opencv-python==4.10.0.84
    - opencv-python-headless==4.10.0.84
    - outcome==1.3.0.post0
    - pandas==1.5.3
    - patool==1.12
    - pillow==11.3.0
    - product-key-memory==0.2.2
    - protobuf==4.25.4
    - py-cpuinfo==9.0.0
    - pydantic==2.10.4
    - pydantic-core==2.27.2
    - pyquaternion==0.9.9
    - pytorch-ignite==0.5.3
    - reformer-pytorch==1.4.4
    - retrying==1.4.2
    - safetensors==0.4.3
    - scikit-image==0.22.0
    - scikit-learn==1.4.0
    - scipy==1.10.1
    - selenium==4.34.2
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - shapely==2.0.5
    - sktime==0.16.1
    - smmap==5.0.1
    - sniffio==1.3.1
    - supervision==0.21.0
    - sympy==1.11.1
    - tensorboard==2.17.0
    - tensorboard-data-server==0.7.2
    - tifffile==2024.8.30
    - timm==1.0.8
    - torch==2.0.1+cu118
    - torchaudio==2.3.1+cu118
    - torchvision==0.15.2+cu118
    - traitlets==5.14.3
    - treelib==1.8.0
    - trio==0.30.0
    - trio-websocket==0.12.2
    - triton==2.0.0
    - typing-extensions==4.14.1
    - ultralytics==8.2.31
    - ultralytics-thop==2.0.17
    - urllib3==1.26.13
    - wandb==0.19.1
    - websocket-client==1.8.0
    - werkzeug==3.1.3
    - widgetsnbextension==4.0.14
    - wsproto==1.2.0
prefix: /root/anaconda3
